TARGET = XCORE-200-EXPLORER
APP_NAME =
USED_MODULES = lib_dsp lib_agc

XCC_FLAGS = -O2 -g

XCORE_ARM_PROJECT = 0
VERBOSE = 0

XMOS_MAKE_PATH ?= ../..
-include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
